MvcPelicula/Models/ErrorViewModel.cs
namespace MvcPelicula.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcPelicula/Models/Pelicula.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace MvcPelicula.Models
{
    public class Pelicula
    {
        public int Id { get; set; }

        [Display(Name = "Título")]
        [Required(ErrorMessage = "El título es obligatorio")]
        public string Titulo { get; set; } = string.Empty;

        [Display(Name = "Fecha de Carga")]
        [DataType(DataType.Date)]
        public DateTime FechaCarga { get; set; }

        [Display(Name = "Género")]
        public string? Genero { get; set; }

        [Display(Name = "Precio")]
        [Required(ErrorMessage = "El precio es obligatorio")]
        public decimal Price { get; set; }
    }
}

MvcPelicula/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPelicula.Models;
using System.Diagnostics;

namespace MvcPelicula.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcPelicula/Controllers/InicioController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPelicula.Models;
using System.Diagnostics;

namespace MvcPelicula.Controllers
{
    public class InicioController : Controller
    {
        private readonly ILogger<InicioController> _logger;

        public InicioController(ILogger<InicioController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcPelicula/Controllers/PeliculaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using MvcPelicula.Datos;
using MvcPelicula.Models;
using System.Diagnostics;
using System.Text.Encodings.Web;
using System.Xml.Linq;
using static Org.BouncyCastle.Crypto.Engines.SM2Engine;

namespace MvcPelicula.Controllers
{
    public class PeliculaController : Controller
    {
        //---- Contexto
        private readonly DbContexto _ContextoDb;

        //---- Objeto 


        public PeliculaController(DbContexto ContextoDb)
        {
            _ContextoDb = ContextoDb;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _ContextoDb.Peliculas.ToListAsync());
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Pelicula pelicula)
        {

            pelicula.FechaCarga = DateTime.Now.Date;

            if (ModelState.IsValid)
            {
                _ContextoDb.Peliculas.Add(pelicula);
                await _ContextoDb.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Pelicula pelicula = _ContextoDb.Peliculas.Find(id);

            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        [HttpGet]
        public IActionResult Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Pelicula pelicula = _ContextoDb.Peliculas.Find(id);

            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                _ContextoDb.Update(pelicula);
                await _ContextoDb.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public IActionResult Eliminar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Pelicula pelicula = _ContextoDb.Peliculas.Find(id);

            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        [HttpPost, ActionName("Eliminar")]
        public async Task<IActionResult> EliminarPelicula(Pelicula pelicula)
        {
            if (_ContextoDb != null && _ContextoDb.Peliculas != null)
            {
                _ContextoDb.Peliculas.Remove(pelicula);
                await _ContextoDb.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcPelicula/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcPelicula/Views/Inicio/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcPelicula/Views/Pelicula/Crear.cshtml
@model MvcPelicula.Models.Pelicula
@{
    ViewData["Title"] = "Nueva Película";
}

<div class="row">
    <div class="offset-12">

        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Crear Nueva Película</strong></h2>
            </div>
            <div class="card-body">
                <form asp-action="Crear" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label class="control-label" asp-for="Titulo">Título</label>
                        <input type="text" class="form-control" asp-for="Titulo" placeholder="Título de película">
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="control-label" asp-for="Genero">Género</label>
                        <input class="form-control" asp-for="Genero" placeholder="Género de película" />
                        <span asp-validation-for="Genero" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="control-label" asp-for="Price">Precio</label>
                        <input class="form-control" asp-for="Price" placeholder="Precio de película" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2 d-flex justify-content-center">
                        <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="Pelicula" asp-action="Index">
                            <i class="fa-solid fa-arrow-left"></i> Regresar
                        </a>

                        <button class="btn btn btn-outline-primary btn-lg w-25" type="submit">
                            <i class="fa-regular fa-floppy-disk"></i> Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MvcPelicula/Views/Pelicula/Detalle.cshtml
@model MvcPelicula.Models.Pelicula
@{
    ViewData["Title"] = "Información de Película";
}

<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Editar Película</strong></h2>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item"><strong>Título: </strong>@Html.DisplayFor(m => m.Titulo)</li>
                    <li class="list-group-item"><strong>Fecha de Carga: </strong>@Html.DisplayFor(m => m.FechaCarga)</li>
                    <li class="list-group-item"><strong>Género: </strong>@Html.DisplayFor(m => m.Genero)</li>
                    <li class="list-group-item"><strong>Precio: </strong>@Html.DisplayFor(m => m.Price)</li>
                    <li class="list-group-item form-group mt-2 d-flex justify-content-center">
                        <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="Pelicula" asp-action="Index">
                            <i class="fa-solid fa-arrow-left"></i> Regresar
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

MvcPelicula/Views/Pelicula/Editar.cshtml
@model MvcPelicula.Models.Pelicula
@{
    ViewData["Title"] = "Editar Película";
}

<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Editar Película</strong></h2>
            </div>
            <div class="card-body">
                <form method="post" asp-action="Editar">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group" hidden>
                        <input class="form-control" asp-for="Id" readonly />
                        <input class="form-control" asp-for="FechaCarga" readonly />
                    </div>

                    <!-- ________________________________________________________________________________________________ -->

                    <div class="form-group">
                        <label class="control-label" asp-for="Titulo">Título</label>
                        <input type="text" class="form-control" asp-for="Titulo" placeholder="Título de película">
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="control-label" asp-for="Genero">Género</label>
                        <input class="form-control" asp-for="Genero" placeholder="Género de película" />
                        <span asp-validation-for="Genero" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="control-label" asp-for="Price">Precio</label>
                        <input class="form-control" asp-for="Price" placeholder="Precio de película" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2 d-flex justify-content-center">
                        <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="Pelicula" asp-action="Index">
                            <i class="fa-solid fa-arrow-left"></i> Regresar
                        </a>

                        <button class="btn btn-outline-warning btn-lg w-25" type="submit">
                            <i class="fa-regular fa-floppy-disk"></i> Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MvcPelicula/Views/Pelicula/Eliminar.cshtml
@model MvcPelicula.Models.Pelicula
@{
    ViewData["Title"] = "Eliminar película";
}

<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h2 class="text-center text-white"><strong>Editar Película</strong></h2>
            </div>
            <div class="card-body">
                <form method="post" asp-action="Eliminar">
                <input hidden asp-for="Id" />
                <ul class="list-group">
                    <li class="list-group-item"><strong>Título: </strong>@Html.DisplayFor(m => m.Titulo)</li>
                    <li class="list-group-item"><strong>Fecha de Carga: </strong>@Html.DisplayFor(m => m.FechaCarga)</li>
                    <li class="list-group-item"><strong>Género: </strong>@Html.DisplayFor(m => m.Genero)</li>
                    <li class="list-group-item"><strong>Precio: </strong>@Html.DisplayFor(m => m.Price)</li>
                    <li class="list-group-item form-group mt-2 d-flex justify-content-center">
                        <a class="btn btn-outline-dark btn-lg w-25 mx-2" asp-controller="Pelicula" asp-action="Index">
                            <i class="fa-solid fa-arrow-left"></i> Regresar
                        </a>

                        <button class="btn btn-outline-danger btn-lg w-25" type="submit">
                            <i class="fa-solid fa-trash"></i> Eliminar
                        </button>
                    </li>
                </ul>
                </form>
            </div>
        </div>
    </div>
</div>

MvcPelicula/Views/Pelicula/Index.cshtml
@model IEnumerable<MvcPelicula.Models.Pelicula>
@{
    ViewData["Title"] = "Listado de Películas";
    int contador = 1;
}

<h2 class="text-center">Listado General</h2>

<div class="row">
    <div class="offset-9 col-3 mb-3">
        <a class="btn btn-outline-dark d-block mx-auto btn-lg" asp-controller="Pelicula"  asp-action="Crear">
            <i class="fa-solid fa-square-plus"></i> Nueva Película
        </a>
    </div>
</div>


<div class="row">
    <div class="offset-12">
        <div class="card">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Lista de Películas</strong></h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @if (Model.Count() > 0)
                    {
                        <table class="table table-hover" id="tablaPeliculas" width="100%" cellspacing="0">
                            <thead>
                                <tr class="bg-black">
                                    <th scope="col" class="text-white">#</th>
                                    <th scope="col" class="text-white">@Html.DisplayNameFor(m => m.Titulo)</th>
                                    <th scope="col" class="text-white">@Html.DisplayNameFor(m => m.FechaCarga)</th>
                                    <th scope="col" class="text-white">@Html.DisplayNameFor(m => m.Genero)</th>
                                    <th scope="col" class="text-white">@Html.DisplayNameFor(m => m.Price)</th>
                                    <th scope="col" class="text-white">Opciones</th>
                                </tr>
                                @foreach (var itemPelicula in Model)
                                {
                                    <tr>
                                        <td>@contador</td>
                                        <td>@Html.DisplayFor(m => itemPelicula.Titulo)</td>
                                        <td>@Html.DisplayFor(m => itemPelicula.FechaCarga)</td>
                                        <td>@Html.DisplayFor(m => itemPelicula.Genero)</td>
                                        <td>$.@Html.DisplayFor(m => itemPelicula.Price)</td>
                                        <td>
                                            <a class="btn btn-outline-primary mx-2" asp-action="Detalle" asp-route-id="@itemPelicula.Id">
                                                <i class="fa-solid fa-circle-info"></i> Detalle
                                            </a>
                                            <a class="btn btn-outline-warning mx-2" asp-action="Editar" asp-route-id="@itemPelicula.Id">
                                                <i class="fa-solid fa-pen-to-square"></i> Editar
                                            </a>
                                            <a class="btn btn-outline-danger mx-2" asp-action="Eliminar" asp-route-id="@itemPelicula.Id">
                                                <i class="fa-solid fa-trash"></i> Eliminar
                                            </a>
                                        </td>
                                    </tr>
                                    contador++;
                                }
                            </thead>
                        </table>
                    }
                    else
                    {
                        <p class="text-center"><strong>No hay registros</strong></p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

MvcPelicula/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcPelicula.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Inicio" asp-action="Index">MvcPelicula</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inicio" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pelicula" asp-action="Index">Películas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inicio" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcPelicula - <a asp-area="" asp-controller="Inicio" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>